trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "This is testing"
  - bash: echo $(PipelineLevelvariable)
  - bash: echo $(Build.BuildId)
  - bash: echo $(Build.BuildNumber)
  - bash: echo $(Build.SourceBranchName)
  - bash: echo $(Build.SourcesDirectory)
  - bash: echo $(Build.SourceVersion)
  - bash: echo $(Build.ArtifactStagingDirectory)
  - bash: java -version
  - bash: npm -version
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.yaml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - bash: ls -R $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  






